# Generated by Django 4.2.7 on 2023-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
