# Generated by Django 4.2.7 on 2023-11-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_messages_r_user_id_alter_messages_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='r_user_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='contact_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_id', to='chats.contacts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='r_contact_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r_contact_id', to='chats.contacts'),
            preserve_default=False,
        ),
    ]
