# Generated by Django 4.2.7 on 2023-11-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_messages_r_user_id_remove_messages_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='send_status',
            field=models.CharField(choices=[('sended', 'sended'), ('sending', 'sending')], default='sending', max_length=10),
        ),
    ]
