# Generated by Django 4.2.7 on 2023-11-24 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0006_messages_send_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='r_contact_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
